name: Windows Command Prompt Testing

on: 
  push:
    branch: [ master ]

jobs:
  build:
    run-ons: windows-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Environments
        run: set

      - name: Architect
        run: wmic OS get OSArchitecture
